name: Deploy to renju-note on release
on:
  release:
    types:
    - published
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/cache@v2
      with:
        path: './node_modules'
        key: ${{ runner.os }}.node_modules.${{ hashFiles('yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
      env:
        CI: 'false'
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RENJU_NOTE }}'
        channelId: live
        projectId: renju-note
