name: Deploy to renju-note on release
on:
  release:
    types:
    - published
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        yarn install --frozen-lockfile
        CI=false yarn build
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RENJU_NOTE }}'
        channelId: live
        projectId: renju-note
